export const by_pos_and_sku = [
    {
        customer_id: 1,
        pos_name: "Aman 400",
        pos_parent_name: "Aman",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 1,
        sku_name: "Zbidelj crni XL",
        sku_parent_name: "Zbidelj",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 10044,
        order_amount: 16417,
        diff: 6373,
        diff_perc: 0.63,
    },
    {
        customer_id: 1,
        pos_name: "Aman 400",
        pos_parent_name: "Aman",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 2,
        sku_name: "Zbidelj braon XL",
        sku_parent_name: "Zbidelj",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 26865,
        order_amount: 24943,
        diff: -1922,
        diff_perc: -0.07,
    },
    {
        customer_id: 1,
        pos_name: "Aman 400",
        pos_parent_name: "Aman",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 3,
        sku_name: "Zbidelj crni M",
        sku_parent_name: "Zbidelj",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 26449,
        order_amount: 14427,
        diff: -12022,
        diff_perc: -0.45,
    },
    {
        customer_id: 1,
        pos_name: "Aman 400",
        pos_parent_name: "Aman",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 4,
        sku_name: "Zbidelj braon M",
        sku_parent_name: "Zbidelj",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 26146,
        order_amount: 18381,
        diff: -7765,
        diff_perc: -0.3,
    },
    {
        customer_id: 1,
        pos_name: "Aman 400",
        pos_parent_name: "Aman",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 5,
        sku_name: "Kukuruz 500ml",
        sku_parent_name: "Kuruz",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 24131,
        order_amount: 13622,
        diff: -10509,
        diff_perc: -0.44,
    },
    {
        customer_id: 1,
        pos_name: "Aman 400",
        pos_parent_name: "Aman",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 6,
        sku_name: "Kukuruz 500ml",
        sku_parent_name: "Kuruz",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 23909,
        order_amount: 20547,
        diff: -3362,
        diff_perc: -0.14,
    },
    {
        customer_id: 2,
        pos_name: "Aman 123",
        pos_parent_name: "Aman",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 1,
        sku_name: "Zbidelj crni XL",
        sku_parent_name: "Zbidelj",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 20842,
        order_amount: 27855,
        diff: 7013,
        diff_perc: 0.34,
    },
    {
        customer_id: 2,
        pos_name: "Aman 123",
        pos_parent_name: "Aman",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 2,
        sku_name: "Zbidelj braon XL",
        sku_parent_name: "Zbidelj",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 20532,
        order_amount: 28315,
        diff: 7783,
        diff_perc: 0.38,
    },
    {
        customer_id: 2,
        pos_name: "Aman 123",
        pos_parent_name: "Aman",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 3,
        sku_name: "Zbidelj crni M",
        sku_parent_name: "Zbidelj",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 27521,
        order_amount: 26883,
        diff: -638,
        diff_perc: -0.02,
    },
    {
        customer_id: 2,
        pos_name: "Aman 123",
        pos_parent_name: "Aman",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 4,
        sku_name: "Zbidelj braon M",
        sku_parent_name: "Zbidelj",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 20107,
        order_amount: 26890,
        diff: 6783,
        diff_perc: 0.34,
    },
    {
        customer_id: 2,
        pos_name: "Aman 123",
        pos_parent_name: "Aman",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 5,
        sku_name: "Kukuruz 500ml",
        sku_parent_name: "Kuruz",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 22316,
        order_amount: 12147,
        diff: -10169,
        diff_perc: -0.46,
    },
    {
        customer_id: 2,
        pos_name: "Aman 123",
        pos_parent_name: "Aman",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 6,
        sku_name: "Kukuruz 500ml",
        sku_parent_name: "Kuruz",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 19071,
        order_amount: 12767,
        diff: -6304,
        diff_perc: -0.33,
    },
    {
        customer_id: 3,
        pos_name: "Aman 121",
        pos_parent_name: "Aman",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 1,
        sku_name: "Zbidelj crni XL",
        sku_parent_name: "Zbidelj",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 16013,
        order_amount: 18389,
        diff: 2376,
        diff_perc: 0.15,
    },
    {
        customer_id: 3,
        pos_name: "Aman 121",
        pos_parent_name: "Aman",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 2,
        sku_name: "Zbidelj braon XL",
        sku_parent_name: "Zbidelj",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 28822,
        order_amount: 16876,
        diff: -11946,
        diff_perc: -0.41,
    },
    {
        customer_id: 3,
        pos_name: "Aman 121",
        pos_parent_name: "Aman",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 3,
        sku_name: "Zbidelj crni M",
        sku_parent_name: "Zbidelj",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 28987,
        order_amount: 11083,
        diff: -17904,
        diff_perc: -0.62,
    },
    {
        customer_id: 3,
        pos_name: "Aman 121",
        pos_parent_name: "Aman",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 4,
        sku_name: "Zbidelj braon M",
        sku_parent_name: "Zbidelj",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 13441,
        order_amount: 14368,
        diff: 927,
        diff_perc: 0.07,
    },
    {
        customer_id: 3,
        pos_name: "Aman 121",
        pos_parent_name: "Aman",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 5,
        sku_name: "Kukuruz 500ml",
        sku_parent_name: "Kuruz",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 29848,
        order_amount: 26879,
        diff: -2969,
        diff_perc: -0.1,
    },
    {
        customer_id: 3,
        pos_name: "Aman 121",
        pos_parent_name: "Aman",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 6,
        sku_name: "Kukuruz 500ml",
        sku_parent_name: "Kuruz",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 27134,
        order_amount: 28538,
        diff: 1404,
        diff_perc: 0.05,
    },
    {
        customer_id: 4,
        pos_name: "Maxi 20",
        pos_parent_name: "Maxi",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 1,
        sku_name: "Zbidelj crni XL",
        sku_parent_name: "Zbidelj",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 19805,
        order_amount: 10725,
        diff: -9080,
        diff_perc: -0.46,
    },
    {
        customer_id: 4,
        pos_name: "Maxi 20",
        pos_parent_name: "Maxi",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 2,
        sku_name: "Zbidelj braon XL",
        sku_parent_name: "Zbidelj",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 29395,
        order_amount: 29755,
        diff: 360,
        diff_perc: 0.01,
    },
    {
        customer_id: 4,
        pos_name: "Maxi 20",
        pos_parent_name: "Maxi",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 3,
        sku_name: "Zbidelj crni M",
        sku_parent_name: "Zbidelj",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 12853,
        order_amount: 16490,
        diff: 3637,
        diff_perc: 0.28,
    },
    {
        customer_id: 4,
        pos_name: "Maxi 20",
        pos_parent_name: "Maxi",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 4,
        sku_name: "Zbidelj braon M",
        sku_parent_name: "Zbidelj",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 25612,
        order_amount: 21179,
        diff: -4433,
        diff_perc: -0.17,
    },
    {
        customer_id: 4,
        pos_name: "Maxi 20",
        pos_parent_name: "Maxi",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 5,
        sku_name: "Kukuruz 500ml",
        sku_parent_name: "Kuruz",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 20383,
        order_amount: 26383,
        diff: 6000,
        diff_perc: 0.29,
    },
    {
        customer_id: 4,
        pos_name: "Maxi 20",
        pos_parent_name: "Maxi",
        channel: "General Trade",
        trade_category: "Grocery Shop",
        item_id: 6,
        sku_name: "Kukuruz 500ml",
        sku_parent_name: "Kuruz",
        sku_brand_name: "Zbidelj vita",
        pos_has_ordered_check: "yes",
        pos_color: "red",
        suggested_amount: 26912,
        order_amount: 10197,
        diff: -16715,
        diff_perc: -0.62,
    },
];

export const by_sku = [
    {
      item_id: 1,
      sku_name: "Zbidelj crni XL",
      sku_parent_name: "Zbidelj",
      sku_brand_name: "Zbidelj vita",
      sub_category: "voce",
      category: "hrana",
      suggested_amount_for_pos_that_ordered: 23360,
      suggested_amount_total: 27136,
      order_amount: 27534,
      diff: 398,
      diff_perc: 0.01,
      total_suggested_perc_reached: 0.8,
    },
    {
      item_id: 2,
      sku_name: "Zbidelj braon XL",
      sku_parent_name: "Zbidelj",
      sku_brand_name: "Zbidelj vita",
      sub_category: "voce",
      category: "hrana",
      suggested_amount_for_pos_that_ordered: 28503,
      suggested_amount_total: 16567,
      order_amount: 27944,
      diff: 11377,
      diff_perc: 0.69,
      total_suggested_perc_reached: 0.8,
    },
    {
      item_id: 3,
      sku_name: "Zbidelj crni M",
      sku_parent_name: "Zbidelj",
      sku_brand_name: "Zbidelj vita",
      sub_category: "voce",
      category: "hrana",
      suggested_amount_for_pos_that_ordered: 13841,
      suggested_amount_total: 17538,
      order_amount: 16108,
      diff: -1430,
      diff_perc: -0.08,
      total_suggested_perc_reached: 0.8,
    },
    {
      item_id: 4,
      sku_name: "Zbidelj braon M",
      sku_parent_name: "Zbidelj",
      sku_brand_name: "Zbidelj vita",
      sub_category: "voce",
      category: "hrana",
      suggested_amount_for_pos_that_ordered: 29422,
      suggested_amount_total: 28025,
      order_amount: 10628,
      diff: -17397,
      diff_perc: -0.62,
      total_suggested_perc_reached: 0.79,
    },
    {
      item_id: 5,
      sku_name: "Kukuruz 500ml",
      sku_parent_name: "Kuruz",
      sku_brand_name: "Zbidelj vita",
      sub_category: "povrce",
      category: "hrana",
      suggested_amount_for_pos_that_ordered: 14333,
      suggested_amount_total: 15277,
      order_amount: 16427,
      diff: 1150,
      diff_perc: 0.08,
      total_suggested_perc_reached: 0.8,
    },
    {
      item_id: 6,
      sku_name: "Kukuruz 500ml",
      sku_parent_name: "Kuruz",
      sku_brand_name: "Zbidelj vita",
      sub_category: "povrce",
      category: "hrana",
      suggested_amount_for_pos_that_ordered: 16891,
      suggested_amount_total: 13171,
      order_amount: 14283,
      diff: 1112,
      diff_perc: 0.08,
      total_suggested_perc_reached: 0.8,
    },
  ];

  